### ISSUE TITLE
Unable to run Crawler.scala files

### ISSUE THREAD

**Issue by JustHarsh** [SlimShadyIAm/DetectYourZen#2]
I tried to run the CrawlerNew.scala file using scalac. I chose to do so because running it with sbt (as suggested in the readme) was giving me an error related to "SecurityManager" in java.

When I tried to run `scalac CrawlerNew.scala` I got an error -

```
-- [E006] Not Found Error: CrawlerNew.scala:1:7 --------------------------------
1 |import ch.uzh.ifi.seal.lisa.core._
  |       ^^
  |       Not found: ch
  |
  | longer explanation available when compiling with `-explain`
1 error found
```

I have not made any changes to the `build.sbt` file. I am running it pretty much just as given in the repo. @SlimShadyIAm, can please help me out with this?

We are using this repo for a research study at the [University of Alberta](https://www.ualberta.ca/index.html) on python and Jupyter notebooks.

**Comment by SlimShadyIAm** [comment]
Hi,
I'll try to take a look at this later today. But regarding the SecurityManager issue, I believe you need to run with Java 8. Could you also try that?

**Comment by SlimShadyIAm** [comment]
Hi,
I just tried running it with a newer version of Java (17 I believe), and I also encountered the `SecurityManager` deprecation error. A quick Google search led me here: https://stackoverflow.com/questions/76151072/error-during-sbt-launcher-java-lang-unsupportedoperationexception-the-security which says to use Java 8.

After installing Java 8 and running `sbt 'runMain CrawlerNew ./data-new'` it compiled and ran just fine for me.

Could you please try this?
